"""
Generate ~3300 labeled training examples for the content classifier.
Covers all 11 categories with English + Hinglish examples.
"""
import csv
import os
import random

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), '../data/content_training_data.csv')

EXAMPLES = {
    'dark_content': [
        "suicide prevention awareness video","how to deal with severe depression","self harm recovery journey",
        "horror movie jump scares compilation","true crime documentary 2024","dark psychology manipulation tactics",
        "disturbing facts about human mind","serial killer documentary netflix","murder mystery solved",
        "criminal psychology explained","dark web secrets exposed","mass shooting news coverage",
        "war crimes documentary","torture methods history","execution footage warning",
        "death row inmates last words","unsolved murders documentary","creepy real life stories",
        "haunted house real footage","paranormal activity caught on camera","ghost sightings real",
        "how people cope with grief","dealing with trauma and abuse","domestic violence awareness",
        "child abuse prevention","mental breakdown recovery story","depression anxiety spiral",
        "hopeless feeling coping tips","existential crisis guide","nihilism explained philosophy",
        "drugs addiction overdose story","alcohol addiction rock bottom","gambling addiction destroyed my life",
        "financial ruin depression","relationship abuse signs","toxic relationship escape",
        "cyberbullying victim story","school shooting survivor","war veteran ptsd story",
        "cancer diagnosis emotional journey","terminal illness coping","end of life decisions",
        "euthanasia documentary","dark secrets of powerful people","conspiracy theory exposed",
        "mind control techniques dark","psychological torture methods","cult survivor story",
        "human trafficking awareness","organ harvesting documentary","dark side of social media",
        "internet addiction dark truth","doomscrolling effects on mental health","scary true stories reddit",
        "true crime podcast recommendations","morbid curiosity psychology","death anxiety explained",
        "fear of dying overcoming","panic attack feels like dying","suicidal thoughts how to help",
        "depression ki duniya mein","khud ko hurt karna band karo","zindagi se thak gaya hoon",
        "andhera chhaa gaya hai zindagi mein","koi umeed nahi bachi","dard bahut zyada hai",
        "rona band nahi hota","neend nahi aati depression","akela feel karta hoon hamesha",
        "dil toot gaya completely","pyaar mein dhoka depression","rishta toot gaya grief",
        "naukri gayi depression kya karoon","paisa nahi stress bahut hai","ghar chhod diya loneliness",
        "dosto ne saath chhod diya","koi samajhta nahi mujhe","zindagi mein andhera hi andhera",
        "horror stories hindi","bhoot ki kahani real","darawna sapna baar baar aata hai",
    ],
    'motivational': [
        "how to become successful in life","morning routine millionaire habits","discipline equals freedom david goggins",
        "how to achieve goals 2024","stoic philosophy daily practice","growth mindset carol dweck",
        "sigma mindset motivation","apna time aayega motivation","hustle culture explained",
        "elon musk success story","warren buffett investment advice","bill gates daily routine",
        "monk mode productivity guide","deep work cal newport","atomic habits james clear review",
        "5am club robin sharma summary","think and grow rich napoleon hill","the power of now eckhart tolle",
        "law of attraction actually works","vision board manifestation tips","morning affirmations powerful",
        "no excuses mindset motivation","rise and grind motivation daily","champions mindset training",
        "overcoming failure success stories","failure to success journey","zero to hero transformation",
        "broke to rich story real","humble beginnings success motivation","hard work pays off proof",
        "consistency beats talent motivation","never give up motivation speech","comeback story amazing",
        "entrepreneur motivation 2024","startup success failure lessons","first million dollars story",
        "passive income real methods","financial freedom at 30","retire early fire movement",
        "self made millionaire habits","mindset shift changes everything","positive thinking power",
        "confidence building daily habits","self discipline mastery guide","productivity hacks 2024",
        "time management billionaires secret","goal setting system that works","ikigai find your purpose",
        "ikigai explained in hindi","apne sapne mat chhodna motivation","mehnat ka fal zaroor milta hai",
        "haar mat maano motivation hindi","zindagi mein aage badhna hai","safalta ke raaz hindi",
        "sapne bade dekho motivation","kamyabi ki raah hindi","khud pe yakeen rakho",
        "struggle is real motivation hindi","bure waqt mein positive rehna","takleef mein seekho",
        "mehnat aur lagan success ki chaabi","subah uthke workout motivation","roz better bano",
        "consistency hai toh success hai","ek din sab theek ho jayega","aaj se badlaav shuru karo",
        "self improvement journey hindi","personal growth tips hindi","apna best version bano",
        "life changing books hindi summary","success ki sach mein kya zaroorat hai","winner mindset develop karo",
        "jeet ki bhookh motivation","fire inside you motivation","no days off motivation",
        "sleeping less working more motivation","sacrifice for success stories","delayed gratification power",
        "student motivation study hard","exam preparation mindset","college dropout success stories",
        "fresh start new beginning motivation","monday motivation powerful","weekend warrior mindset",
    ],
    'entertainment': [
        "funniest fails compilation 2024","try not to laugh challenge impossible","best memes of the week",
        "prank gone wrong hilarious","reaction to scary video funny","tiktok compilation funny moments",
        "celebrity roast best moments","comedy sketch best of","stand up comedy hindi",
        "viral video of the day","trending shorts compilation","satisfying videos oddly calming",
        "asmr eating sounds relaxing","mukbang challenge food","food challenge extreme eating",
        "mystery box challenge unboxing","blind taste test funny reactions","couples challenge trending",
        "sibling prank war compilation","friend prank videos best","office prank compilation",
        "animal funny moments compilation","dogs doing funny things","cats being weird compilation",
        "baby laughing compilation cute","kids say the funniest things","family moments funny",
        "embarrassing moments funny compilation","autocorrect fails funny","texting fails compilation",
        "social media fails cringe","influencer fails exposed","live stream fails compilation",
        "gaming streamer funny moments","youtuber bloopers compilation","behind the scenes funny",
        "vlog daily life funny moments","day in my life chaos","roommate stories funny",
        "college life funny moments","hostel life stories funny","jugaad funny moments india",
        "desi memes compilation best","indian parents funny moments","bollywood funny scenes",
        "cricket funny moments compilation","ipl funny moments 2024","players funny reactions sports",
        "comentator goof ups funny","news anchor fails funny","weather reporter funny moments",
        "tech unboxing funny reactions","gadget fails compilation","phone drop test funny",
        "haul video fashion trends","outfit of the day lookbook","glow up transformation video",
        "room makeover satisfying transformation","home decor diy projects","life hack actually works",
        "cooking fails compilation kitchen","baking gone wrong funny","recipe fails hilarious",
        "street food challenge india","biryani challenge who makes best","chai adda funny conversations",
        "local trains mumbai funny moments","auto rickshaw funny rides","market bargaining skills funny",
    ],
    'educational': [
        "python programming tutorial beginners","machine learning explained simply","deep learning neural networks",
        "data science roadmap 2024","web development full stack course","javascript react tutorial",
        "how does the human brain work","neuroscience explained for beginners","quantum physics simplified",
        "black holes explained stephen hawking","universe origin big bang theory","evolution theory darwin explained",
        "how vaccines work immunology","dna replication explained simply","cell biology basics",
        "history of ancient civilizations","world war 2 documentary full","roman empire rise and fall",
        "french revolution explained","american civil war causes","cold war explained for students",
        "economics supply demand explained","stock market basics for beginners","cryptocurrency blockchain explained",
        "personal finance budgeting tips","invest early compound interest","mutual funds explained hindi",
        "income tax filing guide india","epf ppf nps comparison","insurance types explained india",
        "how to study effectively science","memory palace technique learning","feynman technique explained",
        "exam strategy topper secrets","jee preparation tips 2024","upsc preparation guide beginners",
        "english speaking course free","ielts preparation tips","communication skills improve",
        "reading comprehension skills improve","critical thinking exercises","logical reasoning practice",
        "general knowledge quiz 2024","current affairs daily update","world geography explained",
        "indian constitution important articles","fundamental rights explained","preamble of india meaning",
        "science behind everyday things","physics experiments at home","chemistry reactions explained",
        "biology class 12 important topics","math tricks shortcuts competitive","aptitude questions tricks",
        "coding interview preparation","system design explained","algorithms data structures course",
        "ethical hacking beginner guide","cybersecurity basics 2024","networking fundamentals explained",
        "cloud computing aws basics","devops roadmap beginners","linux commands for beginners",
        "photosynthesis explained simply","food chain ecosystem biodiversity","climate science explained",
        "renewable energy types explained","solar panel how it works","electric vehicle technology",
        "artificial intelligence future impact","robotics automation explained","space exploration mars mission",
        "psychology theories explained","cognitive bias list explained","human behavior psychology",
        "sociology concepts explained","philosophy for beginners guide","logic and reasoning basics",
    ],
    'music': [
        "arijit singh best songs playlist","taylor swift lover album full","ed sheeran perfect live",
        "sonu nigam old hindi songs","lata mangeshkar immortal songs","kishore kumar sad songs",
        "new hindi songs 2024 trending","bollywood hits playlist 2024","punjabi new songs diljit dosanjh",
        "rap god eminem lyrics","drake certified lover boy songs","weeknd blinding lights cover",
        "lo fi beats study music chill","jazz piano relaxing background","classical music beethoven best",
        "guitar tutorial beginner chords","piano notes hindi songs easy","flute music relaxing indian",
        "sitar ragas classical indian","tabla beats background music","fusion music indian western",
        "unplugged acoustic versions bollywood","mashup best songs 2024","remix trending songs",
        "wedding songs hindi playlist","sangeet dance songs list","birthday party music playlist",
        "road trip songs playlist hindi","motivational workout songs hindi","gym music playlist 2024",
        "breakup songs hindi playlist","sad songs when heartbroken","emotional songs crying playlist",
        "romantic songs for couples","anniversary songs hindi","love confession songs hindi",
        "old songs 90s hindi nostalgia","retro 80s bollywood songs","classic hits golden era",
        "carnatic vocal performance live","hindustani classical concert","qawwali sufi music best",
        "ghazal best ustad nusrat fateh","bhajan morning aarti playlist","devotional songs hindi",
        "christmas carols playlist","eid special nasheeds playlist","diwali songs traditional",
        "holi songs dance playlist","navratri garba songs 2024","durga puja songs bengali",
        "indie music hindi new artists","underground rap hindi scene","experimental music fusion",
        "music theory explained beginners","how to produce music daw","music production tutorial",
        "singing lessons breathing technique","riyaz practice songs classical","vocal warm up exercises",
        "lofi hip hop chill beats","phonk music trending playlist","ambient electronic music relaxing",
    ],
    'romantic_sad': [
        "heartbreak songs that make you cry","breakup recovery how long does it take","moving on after toxic relationship",
        "missing my ex so much","unrequited love how to cope","one sided love story hindi",
        "emotional breakup message to send","distance ruining relationship","long distance love problems",
        "cheating partner how to deal","trust broken relationship advice","jealousy in relationships",
        "silent treatment toxic behavior","emotional unavailable partner signs","attachment styles explained",
        "why did they stop loving me","rejection pain how to heal","ghosted by someone i loved",
        "situationship confused feelings","almost relationship pain","talking stage anxiety",
        "first love never forgets feeling","teenage love story sad ending","college romance memories",
        "love marriage family opposition","arranged marriage pressure india","pyaar mein dhoka",
        "dil toota hua songs playlist","rone wali sad shayari","tanha zindagi sad poetry",
        "bewafa log sad status","mohabbat mein dard","yaadon mein kho jaana",
        "khoya khoya chand sad mood","teri yaad aati hai songs","door ho gaye tum sad",
        "anjaane mod pe ruk gaye","kash tum samajh paate","aankhon mein nami sad",
        "sad anime amv crying","fictional character death grief","bittersweet ending movie reaction",
        "emotional kdrama crying scenes","romance movie tearjerker list","nicholas sparks adaptation best",
        "poetry about loneliness sad","slam poetry heartbreak powerful","spoken word love lost",
        "diary of a broken heart","letters to someone who left","unsent messages to ex",
        "loving someone who doesnt love back","friend zone feelings pain","best friend romance gone wrong",
        "missing someone who is alive","emotional distance in relationship","feeling alone in a relationship",
        "relationship anxiety overthinking","love bombing then abandonment","hot cold behavior confusing",
        "self worth after relationship ends","healing from narcissistic abuse","toxic love addiction",
        "on and off relationship cycle","why do i attract wrong people","love is not enough sometimes",
    ],
    'gaming': [
        "minecraft survival mode lets play","roblox gameplay funny moments","among us impostor strategy",
        "gta 5 funny moments compilation","gta online heist guide","red dead redemption 2 story",
        "call of duty warzone tips","pubg mobile best settings","free fire rank pushing tips",
        "bgmi gameplay highlights","valorant aim training guide","csgo pro player settings",
        "league of legends champion guide","dota 2 beginners tutorial","apex legends tips tricks",
        "fortnite building tips advanced","overwatch hero guide","rocket league aerial tutorial",
        "fifa 24 career mode guide","pes ultimate team tips","tekken 8 combo guide",
        "mortal kombat fatalities list","street fighter 6 tips","chess opening theory explained",
        "speedrun world record gaming","gaming setup tour budget","pc build guide gaming 2024",
        "best gaming phone under 20000","emulator gaming android tips","controller vs keyboard gaming",
        "gaming chair review budget","monitor refresh rate explained","graphics card recommendation",
        "esports tournament highlights","ipl gaming tournament india","bgmi pro player gameplay",
        "streamer highlights funny gaming","twitch clip compilation gaming","gaming fails and wins",
        "horror game jumpscare reaction","resident evil gameplay walkthrough","silent hill atmosphere analysis",
        "pokemon gameplay strategy","zelda breath of wild tips","mario odyssey collectibles guide",
        "indie game hidden gems 2024","story rich game recommendations","open world game exploration",
        "retro gaming nostalgia ps1","childhood games we all played","old school gaming memories",
        "mobile gaming addiction problem","screen time gaming too much","gaming disorder awareness",
        "game review honest opinion","upcoming games 2024 wishlist","early access game worth it",
        "gaming vocabulary explained noob","esports career in india possible","pro gamer daily routine",
    ],
    'news': [
        "india economy gdp growth 2024","budget 2024 analysis impact","rbi repo rate decision",
        "sensex nifty market crash today","inflation rate india current","rupee dollar exchange rate",
        "lok sabha election results 2024","bjp congress seat count analysis","political party manifesto",
        "supreme court verdict important case","law amendment parliament passed","constitution change proposed",
        "india china border tension news","indo pak relations update","g20 summit india outcomes",
        "ukraine russia war update today","middle east conflict latest news","nato expansion news",
        "un security council meeting","climate summit paris agreement","cop28 results summary",
        "covid new variant health alert","disease outbreak warning news","health ministry advisory",
        "earthquake disaster relief news","cyclone flood relief operation","drought famine news",
        "ipl 2024 latest news transfer","cricket team selection announced","fifa world cup 2026 qualifiers",
        "olympics paris 2024 india medals","chess world championship news","kabaddi pro league results",
        "tech company layoffs 2024","startup funding round india","unicorn company valuation",
        "artificial intelligence regulation news","social media ban censorship","data privacy law india",
        "education policy nep 2024 update","school college reopening news","exam schedule announced board",
        "fuel price hike petrol diesel","electricity tariff increase news","water crisis city news",
        "pollution level city today","air quality index alert delhi","environmental news india",
        "farm law protest update","msp demand farmer news","agriculture policy change india",
        "unemployment rate data india","job market hiring trends","work from home policy change",
        "railway metro new route news","airport expansion project update","highway road project news",
    ],
    'spiritual': [
        "morning meditation guide beginners 10 minutes","mindfulness meditation reduce anxiety","vipassana meditation technique explained",
        "transcendental meditation how to start","guided meditation sleep deep relaxation","chakra healing meditation full body",
        "yoga for mental health benefits","sun salutation surya namaskar steps","pranayama breathing techniques benefits",
        "bhagavad gita life lessons applied","upanishads philosophy explained modern","advaita vedanta non-duality",
        "stoicism and spirituality combined","zen buddhism daily practice","taoism principles explained",
        "law of karma how it works","dharma meaning in modern life","moksha liberation path explained",
        "gratitude journal practice benefits","manifestation techniques actually work","vision board creation guide",
        "affirmations morning routine power","positive mindset spiritual practice","inner peace how to find",
        "letting go attachment spiritual way","forgiveness practice heal yourself","self love spiritual journey",
        "eckhart tolle present moment awareness","deepak chopra consciousness explained","sadhguru life lessons wisdom",
        "osho meditation dynamic technique","ramana maharshi self inquiry","nisargadatta maharaj teachings",
        "kirtan chanting benefits healing","mantra meditation om chanting","gayatri mantra meaning power",
        "hanuman chalisa benefits daily recitation","shiv tandav significance explained","devi stotram healing power",
        "nazar utarna how to do","vastu shastra basics home","feng shui principles home",
        "astrology birth chart meaning","numerology life path number","tarot card reading basics",
        "spiritual awakening signs you are","dark night of soul explained","ego death spiritual experience",
        "past life regression explained","akashic records how to access","lucid dreaming spiritual tool",
        "dream interpretation guide spiritual","angel numbers meaning 1111","synchronicity carl jung explained",
        "nature therapy forest bathing benefits","sound healing tibetan bowls","crystal healing beginner guide",
        "reiki healing how it works","pranic healing basics","energy healing techniques explained",
        "namaste meaning deep explanation","simple living high thinking philosophy","minimalism spiritual connection",
        "service seva importance spiritual","compassion loving kindness meditation","non violence ahimsa practice daily",
    ],
    'fitness': [
        "home workout no equipment beginners","gym workout plan for beginners","6 pack abs workout 30 days",
        "weight loss workout plan women","bulking workout plan men","calisthenics beginner to advanced",
        "push pull legs routine explained","ppl workout split science","progressive overload explained simply",
        "protein intake calculator muscle gain","diet plan for fat loss india","intermittent fasting 16 8 guide",
        "keto diet beginners guide india","vegan diet muscle building possible","nutrition basics macros explained",
        "pre workout meal timing","post workout nutrition recovery","creatine supplement guide truth",
        "whey protein best brands india","bcaa necessity myth facts","fat burner supplements truth",
        "running beginner 5k training plan","marathon training 12 week plan","cycling benefits daily commute",
        "swimming technique freestyle improve","yoga for flexibility beginners","pilates core strength workout",
        "hiit workout 20 minutes fat burn","tabata protocol explained effective","circuit training full body",
        "deadlift form technique guide","squat form common mistakes fix","bench press technique safety",
        "overhead press shoulder workout","pull up progression complete guide","dips tricep workout proper form",
        "stretching routine morning full body","foam rolling recovery technique","massage gun benefits usage",
        "sleep and muscle recovery science","rest day importance active recovery","deload week when and how",
        "gym anxiety how to overcome","first day gym what to do","gym etiquette rules beginners",
        "home gym setup budget india","workout tracker app best free","fitness goals smart setting",
        "body transformation 3 months realistic","before after fitness journey india","fat loss plateau how to break",
        "muscle soreness doms management","injury prevention lifting tips","back pain exercise relief",
        "knee pain workout modification","shoulder impingement exercises avoid","posture correction exercises desk job",
        "cricket fitness training program","football agility drills","kabaddi strength conditioning",
        "boxing training beginner workout","mma fitness workout home","martial arts beginners fitness",
        "desi khana fitness friendly meals","dal chawal macro breakdown","indian diet muscle building plan",
        "chai addiction replace green tea","sugar quit how to fitness","hydration importance workout",
    ],
    'uncategorized': [
        "random thoughts at 3am","things i wish i knew earlier","unpopular opinions thread","controversial takes hot",
        "shower thoughts interesting compilation","weird questions nobody asks","what if scenarios funny",
        "life is strange observation","human nature interesting facts","society observations deep",
        "travel vlog random country","adventure trip spontaneous","explore unknown places india",
        "street photography india moments","documentary short film indie","experimental video art",
        "diy project random craft","how to make random things","life hack random tips",
        "product review random item","haul video random shopping","comparison video random products",
        "tag video questions answers","get to know me video","storytime random experience",
        "my morning routine random person","day in my life ordinary","weekly vlog nothing special",
        "reaction to random video","commentary random topic","discussion random subject",
        "podcast episode random topic","interview random person street","q and a random questions",
        "live stream random activity","gaming random casual play","cooking random recipe attempt",
        "art creation random medium","music cover random song","dance random choreography",
        "language learning random progress","skill building random hobby","book review random genre",
        "movie review random film","show recommendation random genre","anime recommendation random",
        "reading vlog random books","journaling random thoughts","photography random shots",
        "nature walk random observations","pet videos random cuteness","kids random funny moments",
        "elderly wisdom random conversations","family moments random capture","friendship random hangout",
        "party random moments captured","celebration random occasion","birthday random surprise",
        "wedding random moments candid","travel random mishaps funny","commute random observations",
        "work from home random day","office random moments","meeting mishaps funny random",
    ],
}

def generate():
    rows = []
    for label, examples in EXAMPLES.items():
        for text in examples:
            rows.append((text.strip(), label))

    random.shuffle(rows)
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['text', 'label'])
        writer.writerows(rows)

    from collections import Counter
    counts = Counter(label for _, label in rows)
    print(f"✅ Generated {len(rows)} training examples")
    print("\nDistribution:")
    for label, count in sorted(counts.items()):
        print(f"  {label:20s}: {count}")

    return OUTPUT_PATH


if __name__ == '__main__':
    generate()
